### ISSUE TITLE
Method for Supporting Custom Attributes

### ISSUE THREAD

**Issue by scott-emery** [Telecominfraproject/oopt-tai#15]
I order to create working systems, there are some additional object attributes types which may need to be supported. For example, there may be additional functionality enabled by certain transponders that not all transponders would be expected to support. Or there may be some settings which need to be initialized for proper operation which are specific to one transponder. This github issue is being created to propose a method for supporting these custom attributes and hammer out a solution.

Each TAI object currently has a list of standard attributes and an empty list of custom attributes. The standard attributes are listed in the `tai_<object>_attr_t` enumeration between the `TAI_<OBJECT>_ATTR_START` and `TAI_<OBJECT>_ATTR_END` constants. For example, for the module objects, the taimodule.h file defines an enumeration called `tai_module_attr_t` which lists the standard attributes between the `TAI_MODULE_ATTR_START` and `TAI_MODULE_ATTR_END` constants. These include the `TAI_MODULE_ATTR_LOCATION`, `TAI_MODULE_ATTR_VENDOR_NAME`, `TAI_MODULE_ATTR_NUM_NETWORK_INTERFACES`, and many other attributes.

At the end of this enumeration a range for custom attributes is allocated, but is currently unused. This range starts with the `TAI_<OBJECT>_ATTR_CUSTOM_RANGE_START` constant, which is set to the value 0x10000000. This provides substantial separation from the standard attributes and allows one to easily determine that a attribute's value is in the custom range. Another constant, `TAI_<OBJECT>_ATTR_CUSTOM_RANGE_END` delimits the end of the range of custom attributes.

The proposal to support custom attributes is to add a single line between the `TAI_<OBJECT>_ATTR_CUSTOM_RANGE_START` and `TAI_<OBJECT>_ATTR_CUSTOM_RANGE_END` which is an #include directive to include a file in the new "custom" subdirectory of the "inc" directory. For example, for the module object this line would be `#include "custom/taimodule_custom.h"`. Similar lines would be added for the network interface and host interface objects (and any other objects which get created in the future). The reason for using an #include directive here is to move all custom attributes out of the "standard" TAI include files. I would expect that custom attributes will have more "churn" than the standard attributes and by putting the custom attributes in a separate file from the standard attributes this churn will not impact the standard TAI include files.

The format of the include files in the "custom" directory will simply be a list of attributes, with appropriate comments, of course. We could potentially place #include directives in the `custom/tai<object>_custom.h` files, one for each transponder that has custom attributes, but that seems like overkill at this point.

**Comment by ishidawataru** [comment]
@scott-emery Do we need to create custom header files in this repo to make stub/test compilable? Or are you thinking to use `ifdef` or `autoconf` to make custom headers optional for compile?

**Comment by scott-emery** [comment]
You know, after thinking about this some more, it occurred to me that custom attributes can be supported entirely within the TAI adapter's code. So, for now, I'm closing this issue.
