### ISSUE TITLE
memory access out of range

### ISSUE THREAD

**Issue by oplklum** [Telecominfraproject/oopt-tai#175]
tai_status_t tai_api_initialize(_In_ uint64_t flags,
                                _In_ const tai_service_method_table_t* services)
{
    openlog("stub_tai_adapter", LOG_PID, LOG_USER);
    if (0 != flags) {
        TAI_SYSLOG_ERROR("Invalid flags passed to TAI API initialize");
        return TAI_STATUS_INVALID_PARAMETER;
    }

    if (NULL == services) {
        TAI_SYSLOG_ERROR("Invalid services handle passed to TAI API initialize");
        return TAI_STATUS_INVALID_PARAMETER;
    }

    memcpy(&adapter_host_fns, services, sizeof(adapter_host_fns));
    **memset(g_modules, 0, sizeof(g_modules) * STUB_NUM_MODULE);**
    initialized = true; 

The array size of g_modules is out of range for the below code:
memset(g_modules, 0, sizeof(g_modules) * STUB_NUM_MODULE);
I think it should be:
memset(g_modules, 0, sizeof(g_modules));

Thanks.

**Comment by ishidawataru** [comment]
@oplklum Thanks for the report. I opened a PR to fix the issue.
