### ISSUE TITLE
Confirmation of TAI_NETWORK_INTERFACE_ATTR_DSP_STATUS.

### ISSUE THREAD

**Issue by JumpeiHongo** [Telecominfraproject/oopt-tai#35]
Hi everyone, I think user who use the CFP2ACO want to know the two kind of the FAULT alarm for ACO and DSP.
As of now, it looks there is one FAULT alarm in "TAI_NETWORK_INTERFACE_ATTR_OPER_STATUS".
This FAULT alarm is for ACO. Is that right?

And I think we need RMV alarm for maintenance.

What do you think if I add the following new ID for DSP?
_tai_network_interface_attr_t
ID: TAI_NETWORK_INTERFACE_ATTR_DSP_OPER_STATUS
type(parameter): RMV or FAULT
But I also still consider the case of DCO.

Thank you.

**Comment by ishidawataru** [comment]
@JumpeiHongo I agree to have an attribute for DSP status.
What is RMV?
Do we have any reference we can use for this attribute in a spec like OpenROADM, OpenConfig, CFP MSA?

@samisaab I believe this attribute can also be used for DCO transceiver. Am I correct?

**Comment by JumpeiHongo** [comment]
@ishidawataru 
>What it RMV?

"RMV" means the PIU is removed.

>Do we have any reference we can use for this attribute in a spec like OpenROADM, OpenConfig, CFP MSA?

I will confirm if I share the alarm list fr OpenROADM MSA project.

**Comment by JumpeiHongo** [comment]
@ishidawataru
> > Do we have any reference we can use for this attribute in a spec like OpenROADM, OpenConfig, CFP MSA?
> I will confirm if I share the alarm list fr OpenROADM MSA project.

It looks there are only types for alarms below.
https://github.com/OpenROADM/OpenROADM_MSA_Public/tree/master/model/Common

I think the alarms for OpenROADM are vendor specific.

**Comment by ishidawataru** [comment]
oh, I thought what you are saying by DSP status means internal status of DSP (e.g initialization, loss-of-signal etc..)

As for the physical module presence, we have [module_presence](https://github.com/Telecominfraproject/oopt-tai/blob/master/inc/tai.h#L78-L92) callback.

When PIU is removed, we can call this callback with `presence=false`.

**Comment by JumpeiHongo** [comment]
@ishidawataru and all
I see about PIU removed status. thank you.

Could you please confirm below?
http://openroadm.org/download.html
20171121a Open ROADM MSA specification ver 2 00.xlsx

You can understand the alarm for Open ROADM.
Caution to read:
1.This Spec is for Transponder not including the Switch device.
2.If you see this file, you can see "W SWITCH functional" sheet. This is not L2 SWITCH.
