### ISSUE TITLE
Baudrate attribute

### ISSUE THREAD

**Issue by ojnas** [Telecominfraproject/oopt-tai#38]
I could not find any attribute related to baudrate or bitrate. Shouldn't this be a network interface attribute or do you only target modules supporting a single baudrate?

**Comment by scott-emery** [comment]
There is not currently a baudrate/bitrate attribute for the network interface object (or any other object). Currently, the bitrate is indirectly selected based upon the modulation. For the modules I'm familiar with, each modulation technique selects a single network interface bitrate. For example, on the AC400 selecting 16-QAM modulation means the network interface is carrying 200Gbps of host interface traffic.

**Comment by ojnas** [comment]
Yes, it's true that the AC400 and existing pluggable DCO modules only supports a single baudrate so the modulation decides the bitrate. But some system vendors' transponders (using in-house DSPs) already support two baudrates and the AC1200 will support variable baudrate. Maybe TAI doesn't have to support this today but it is something that will need to be considered in the future.

**Comment by ishidawataru** [comment]
I think it is good to have a baud rate attribute in TAI. Thanks for bringing this up.
Even if the DSP doesn't support changing the baud rate, it might be useful to have a read-only attribute to know the current baud rate.

**Comment by HidekiNishizawa** [comment]
I agree to Wataru, baudrate must be read-only parameter from coherent DSP point of view. Generally baudrate is determined after the other setting parameters like modulation format, FEC type, FEC overhead, etc. have been configured.
