### ISSUE TITLE
Clarification: TAI_MODULE_ATTR_TRIBUTARY_MAPPING

### ISSUE THREAD

**Issue by scott-emery** [Telecominfraproject/oopt-tai#42]
Now that this attribute is defined, I'm about to change the implementation of this attribute from a custom attribute to the standard attribute. I have some questions about how the get_attribute function is supposed to work for this. This attribute is basically a list (tai_object_map_list_t) where each element in that list has a nested list (tai_object_list_t).

First off, I assume that the TAI adapter host is responsible for allocating all memory for the attribute prior to calling get_attribute. The TAI adapter is not responsible for allocating any memory in the get_attribute function. This means that the "list" field of the tai_object_map_list_t must point to an array of "count" tai_object_map_t objects. Similarly each tai_object_map_t element in that array must have a "value.list" field which points to an array of "value.count" tai_object_id_t objects. Please chime in if I'm wrong here.

Now, for the questions:

1. Is the "key" field of each tai_object_map_t entry expected to be initialized prior to the get_attribute call, so that only those network interfaces specified have their tributary maps returned? OR Are the "key" fields uninitialized, and the list of tai_object_map_t's is expected to be large enough to hold an entry for every network interface object on a module?

I'm thinking the later (key fields are uninitialized). If the size of the tai_object_map_t array is too small, then the TAI adapter puts the required size in the tai_object_map_list_t's "count" field and returns TAI_STATUS_BUFFER_OVERFLOW. If the tai_object_map_list_t's list is larger than the number of network interfaces to be returned in the tai_object_map_t list, then the TAI adapter sets the tai_object_map_list_t's "count" field to the number of entries it filled and returns TAI_STATUS_SUCCESS. This is generally how arrays are supposed to work in SAI/TAI.

2. And that brings us to the nested lists. If my previous assumption is correct about how SAI/TAI lists work, then the "count" field of each tai_object_list_t entry must be large enough so that the "list" field of the tai_object_list_t entry points to a pre-allocated list of tai_object_id_t's big enough to hold the maximum number of host interfaces that can be mapped to a network interface. If the "count" field of a tai_object_list_t entry is too large, then the TAI adapter will set it to the actual number of host interface object id's it placed in the list. If the "count" field of a tai_object_list_t entry is too small, then the TAI adapter will set the "count" field to the required size and return TAI_STATUS_BUFFER_OVERFLOW. In order to know which list was too small, the TAI adapter host will need to go through the lists, looking for count fields which are larger than what was originally passed to the get_attribute function.

Is this the correct understanding of how the get_attribute function should work for the TAI_MODULE_ATTR_TRIBUTARY_MAPPING attribute?

**Comment by ishidawataru** [comment]
Yes, your understanding is completely same as mine.

**Comment by scott-emery** [comment]
Thank you. Closing this.
