### ISSUE TITLE
Grid spacing 33 GHz

### ISSUE THREAD

**Issue by ojnas** [Telecominfraproject/oopt-tai#46]
Why is 33 GHz included in the grid spacing attribute? This is not aligned with any standard grid as far as I know.

**Comment by scott-emery** [comment]
The list of possible grid spacings was taken from the CFP MSA MIS (http://www.cfp-msa.org/documents.html). See page 82 of the Version 2.6 spec, for CFP NVR4 register 8196. It doesn't really cause any harm to include the 33 GHz possibility, even if nobody is currently implementing it, does it? That value will simply not be listed as something supported.

**Comment by samisaab** [comment]
33 GHz grid spacing is used in legacy 10G submarine systems.  As such, current systems can be required to adhere with the 33 GHz grid.

**Comment by ishidawataru** [comment]
@ojnas Please reopen if you have further questions.
