### ISSUE TITLE
Change fine tune laser frequency attribute from unsigned to signed.

### ISSUE THREAD

**Issue by samisaab** [Telecominfraproject/oopt-tai#47]
MSA defines fine tune frequency register as a signed 16-bit integer with LSB = 1 MHz.  As such, change `TAI_NETWORK_INTERFACE_ATTR_TX_FINE_TUNE_LASER_FREQ` type from unsigned to signed.  It's currently `@type #tai_uint64_t`, so change it to `@type #tai_int64_t`.

**Comment by scott-emery** [comment]
Nice catch! Please open a pull request.
