### ISSUE TITLE
TAI_HOST_INTERFACE_ATTR_LANE_FAULT is not defined properly

### ISSUE THREAD

**Issue by scott-emery** [Telecominfraproject/oopt-tai#53]
Commit 2f2abde98c96c7f5ce85732840c3bd134bece9a9 changed the lane fault definition from a bitmap value to a list of enumerated values. This matches the way SAI handles things. The problem is that a host interface can have multiple lanes, each of which can have faults. So instead of a list of faults, this attribute needs to be a list of lanes each with a list of faults.

This COULD be implemented with the current definition by using a single list, and having the first N entries set aside for lane 0, the next N entries for lane 1, etc.., where N is the number of possible lane faults. But this has two problems:

1. There is currently no way to specify a "no fault" value which would be necessary to fill the end of each lane's list section.
2. This is ugly and wasteful. It artificially creates a two dimensional list from a single dimension list, and requires that a # lanes x # fault reasons list be used.

Instead, I think we need to follow the example of the tributary mapping, and create an attribute which points to a list of lanes, each of which is a list of faults on that lane. Something like this:

A new attribute value is added to the ```tai_attribute_value_t``` union:
```
tai_attr_value_list_t attrvallist;
```
Which is defined as:
```
typedef struct _tai_attr_value_list_t
{
    /** Number of attribute values in the list */
    uint32_t count;

    /** Attribute value list */
    tai_attribute_value_t *list;
} tai_attr_value_list_t;
```

The type of the ```TAI_HOST_INTERFACE_ATTR_LANE_FAULT``` attribute would then be:
```
@type #tai_attr_value_list_t #tai_s32_list_t #tai_host_interface_lane_fault_t
```

**Comment by ishidawataru** [comment]
@scott-emery How about creating a new object `host_interface_lane` ?
I'm not against to create `attrvallist`.
I just thought if we are going to have more lane related attributes, it would be good to have an object for it.

**Comment by scott-emery** [comment]
At some point in the future we could create host_interface_lane objects, but for now, since this is the only attribute of such objects, keeping this as part of the host interface object seem like the best option.

**Comment by ishidawataru** [comment]
@scott-emery Thanks for your comment. Merged the PR.
