### ISSUE TITLE
some issues on TAI-MAI.md

### ISSUE THREAD

**Issue by Lewis-Kang** [Telecominfraproject/oopt-tai#55]
The following APIs or structure is mentioned in https://github.com/Telecominfraproject/oopt-tai/blob/master/docs/TAI-MAI.md

_mai_api_initialize()
mai_api_uninitialize()
mai_service_method_table_t_

However, according to the code in https://github.com/Telecominfraproject/oopt-tai-implementations/tree/master/tai_mux, the following are being used instead 

_tai_api_initialize()
tai_api_uninitialize()
tai_service_method_table_t_

Should TAI-MAI.md be corrected or the code needs to be changed to match with TAI-MAI.md?

Also, the following paragraph in TAI-MAI.md is not complete and it's wrong by saying "a null point for...."

_"After receiving the tai_api_initialize() PA will in turn call Module Adapter's mai_api_initialize() function. There are two parameters passed to the mai_api_initialize() function: flags, which is currently unused and must be set to zero, and a null pointer for mai_service_method_table_t. called"_

**Comment by ishidawataru** [comment]
@Lewis-Kang TAI-MAI.md needs to be updated based on the current mux implementation.

We need to clearly explain that MAI interface is now exactly same as TAI interface. (We could remove the term MAI depending on how to explain.)

We can use the exact same libtai.so without mux or with mux.
When we use the mux, it calls `libtai.so` 's `tai_api_initialize()` with setting [module_presence](https://github.com/Telecominfraproject/oopt-tai/blob/master/inc/tai.h#L104) to `null`.
In this way, libtai.so won't do module detection and rely it on mux.

**Comment by ishidawataru** [comment]
TAI-MAI.md is replaced with TAI-MUX.pdf
