### ISSUE TITLE
Add additional attributes

### ISSUE THREAD

**Issue by scott-emery** [Telecominfraproject/oopt-tai#6]
The object attributes which are currently defined are those attributes which were part of the CFP MSA MIS 2.2. Attributes not in the MSA were deemed vendor-extensions and not included in the TAI. But there are some very important attributes, such as the modulation and signal coding of a network interface, which should be included in the TAI.

I'm opening this issue as a way to keep track of the "non-standard" attributes which should be added to TAI in a standard way.

**Comment by scott-emery** [comment]
As I mentioned in the issue, the modulation format is one of the attributes I'd like to add to the network interface objects. The transponder I'm working with has the following formats, but I suspect there are more.

Please comment on the other modulation formats which should be added to this enum so I can include them in the pull request.

```C
/** @brief The modulation format */
typedef enum _tai_network_interface_modulation_format_t
{
    TAI_NETWORK_INTERFACE_MODULATION_FORMAT_UNKNOWN,
    TAI_NETWORK_INTERFACE_MODULATION_FORMAT_16_QAM,
    TAI_NETWORK_INTERFACE_MODULATION_FORMAT_8_QAM,
    TAI_NETWORK_INTERFACE_MODULATION_FORMAT_PM_QPSK,
    TAI_NETWORK_INTERFACE_MODULATION_FORMAT_MAX
} tai_network_interface_modulation_format_t;
```
The attribute would then be added to the network interface object's standard (not custom) range as:
```C
    /**
    * @brief The modulation format
    *
    * @type #tai_network_interface_modulation_format_t
    */
   TAI_NETWORK_INTERFACE_ATTR_MODULATION_FORMAT,
```

**Comment by scott-emery** [comment]
In addition to the modulation format, some other network interface attributes we could consider adding are:

* Current Pre-FEC Bit Error Rate
* FEC Uncorrectable code blocks since reset
* Differential encoding
* FEC mode
* Master enable
* Transmitter turn-up state
* Receiver turn-up state

Please provide thoughts on these attributes, and others which make sense to add to the standard network interface object attributes.

**Comment by ishidawataru** [comment]
@scott-emery As for modulation type, how about using this?

https://github.com/OpenROADM/OpenROADM_MSA_Public/blob/master/model/Common/org-openroadm-common-optical-channel-types.yang#L162-L218

**Comment by HidekiNishizawa** [comment]
Hi Scott, I am Hideki Nishizawa from NTT labs. Let me ask you about your comment, what do you mean by the word 'master mode'? Is it for control interface like MDIO?

**Comment by HidekiNishizawa** [comment]
I found that you mean master enable.

**Comment by scott-emery** [comment]
@ishidawataru That's a good list. The [CFP MSA](http://www.cfp-msa.org/Documents/CFP_MSA_MIS_V2p6r06a.pdf) has additional formats for qam-64 and qam-256. We should probably add those too. There are also Non-PSK, ODB, and PAM4 options in the MSA. Do you have any opinion on including/excluding those formats?

**Comment by scott-emery** [comment]
@HidekiNishizawa It's easier to think of a module with multiple network interfaces when thinking about TAI. The attributes of a network interface apply to only that one network interface. The attributes of a module apply to the module as a whole, not just one network interface or host interface. So the master enable attribute for a network interface would apply to just the network interface, not the whole module. 

The documentation I have for the master enable of a network interface says "When enabled, network lane modem function will turn-up if MOD_LOPWR is de-asserted."

**Comment by ishidawataru** [comment]
@scott-emery I prefer to keep it simple for now.
Including PAM4 would be very interesting, but I'd like to keep it until when we support PAM4 tranceiver in TAI.

How about the list below?

```c
typedef enum _tai_network_interface_modulation_format_t
{
  TAI_NETWORK_INTERFACE_MODULATION_FORMAT_UNKNOWN,
  TAI_NETWORK_INTERFACE_MODULATION_FORMAT_BPSK,
  TAI_NETWORK_INTERFACE_MODULATION_FORMAT_DP_BPSK,
  TAI_NETWORK_INTERFACE_MODULATION_FORMAT_QPSK,
  TAI_NETWORK_INTERFACE_MODULATION_FORMAT_DP_QPSK,
  TAI_NETWORK_INTERFACE_MODULATION_FORMAT_8_QAM,
  TAI_NETWORK_INTERFACE_MODULATION_FORMAT_DP_8_QAM,
  TAI_NETWORK_INTERFACE_MODULATION_FORMAT_16_QAM,
  TAI_NETWORK_INTERFACE_MODULATION_FORMAT_DP_16_QAM,
  TAI_NETWORK_INTERFACE_MODULATION_FORMAT_64_QAM,
  TAI_NETWORK_INTERFACE_MODULATION_FORMAT_DP_64_QAM,
} tai_network_interface_modulation_format_t;
```

**Comment by HidekiNishizawa** [comment]
@ishidawataru @scott-emery May I add 32QAM as below? Because the latest DSP has not only 64QAM but also 32QAM.

typedef enum _tai_network_interface_modulation_format_t
{
  TAI_NETWORK_INTERFACE_MODULATION_FORMAT_UNKNOWN,
  TAI_NETWORK_INTERFACE_MODULATION_FORMAT_BPSK,
  TAI_NETWORK_INTERFACE_MODULATION_FORMAT_DP_BPSK,
  TAI_NETWORK_INTERFACE_MODULATION_FORMAT_QPSK,
  TAI_NETWORK_INTERFACE_MODULATION_FORMAT_DP_QPSK,
  TAI_NETWORK_INTERFACE_MODULATION_FORMAT_8_QAM,
  TAI_NETWORK_INTERFACE_MODULATION_FORMAT_DP_8_QAM,
  TAI_NETWORK_INTERFACE_MODULATION_FORMAT_16_QAM,
  TAI_NETWORK_INTERFACE_MODULATION_FORMAT_DP_16_QAM,
  TAI_NETWORK_INTERFACE_MODULATION_FORMAT_32_QAM,
  TAI_NETWORK_INTERFACE_MODULATION_FORMAT_DP_32_QAM,
  TAI_NETWORK_INTERFACE_MODULATION_FORMAT_64_QAM,
  TAI_NETWORK_INTERFACE_MODULATION_FORMAT_DP_64_QAM,
} tai_network_interface_modulation_format_t;

**Comment by ishidawataru** [comment]
@HidekiNishizawa ok, let's add 32_QAM as well.

**Comment by scott-emery** [comment]
I'm sure we will have requests to add many more modulation formats in the future. This seems like a good set to start with. Since the pull request for the modulation format has been merged, I'm going to close this issue. From now on, let's open individual issues for each new/modified attribute. I think that will be make it easier to keep track of the status of issues.

Closing issue due to merge of pull request #7
