### ISSUE TITLE
LOF(loss of frame) monitoring function

### ISSUE THREAD

**Issue by JumpeiHongo** [Telecominfraproject/oopt-tai#62]
Hello @ishidawataru , @scott-emery , @samisaab and all,

Can I ask two questions below?
 (1)We'd like to add LOF(loss of frame) monitor
    I guess "tai_host_interface_tx_align_status_t" is it.
    Is that right?
    
 (2)Could you tell me the detection point for "tai_host_interface_tx_align_status_t"?
    It looks it is the point (1) in the attached file.
[Detection.pptx](https://github.com/Telecominfraproject/oopt-tai/files/2893452/Detection.pptx)
    Is that right?

**Comment by ishidawataru** [comment]
@JumpeiHongo `tai_host_interface_tx_align_status_t` is typically [implemented](https://github.com/Telecominfraproject/oopt-tai-implementations/blob/5f555260318f3eb0dce409fd2e58f205f7b7dd68/tai_ac400/src/ac400_tai_hostif.c#L86) as reading `B650` register in [CFP MSA](http://www.cfp-msa.org/Documents/CFP_MSA_MIS_V2p6r06a.pdf).

If you are saying about OTN LOF, `tai_host_interface_tx_align_status_t` is not about that.
We don't have an attribute for OTN LOF in TAI yet.

Your understanding of the detection point is correct.

@scott-emery @samisaab Please correct if I'm wrong.

**Comment by JumpeiHongo** [comment]
Hello @ishidawataru  , @scott-emery  , @samisaab  and all,

Thank you for your comment.

I update the diagram by using current TAI parameter.
[Detection.pptx](https://github.com/Telecominfraproject/oopt-tai/files/2904497/Detection.pptx)
Could you please confirm this?

And I also add the two new parameters in this slide.
Do you have any comment if I add them to the TAI interface?
My concern is there is no concept of OTN in the current TAI interface.

**Comment by ishidawataru** [comment]
@JumpeiHongo Please create a PR for your proposal so that we can discuss based on code.

**Comment by ishidawataru** [comment]
If I understand correctly, LOF status should also be in network interface attribute.
host interface's RX means CAUI-4 interface which faces to Ethernet ASIC. It doesn't carry OTU information.

**Comment by JumpeiHongo** [comment]
Thanks! I will do PR.
