### ISSUE TITLE
Add client signal rate attribute

### ISSUE THREAD

**Issue by skuwa** [Telecominfraproject/oopt-tai#76]
I suggest to support client signal rate attribute.

I propose to add client signal rate attribute under **taihostif**.
Here is my suggestion sample code:

```
typedef enum _tai_host_interface_client_signal_rate_t
{
    TAI_HOST_INTERFACE_CLIENT_SIGNAL_RATE_UNKNOWN,
    TAI_HOST_INTERFACE_CLIENT_SIGNAL_RATE_100_GbE,
    TAI_HOST_INTERFACE_CLIENT_SIGNAL_RATE_200_GbE,
    TAI_HOST_INTERFACE_CLIENT_SIGNAL_RATE_400_GbE,
    TAI_HOST_INTERFACE_CLIENT_SIGNAL_RATE_OTU4,
    TAI_HOST_INTERFACE_CLIENT_SIGNAL_RATE_MAX
} tai_host_interface_client_signal_rate_t;
```

I think the network interface bitrate can be  defined by this client signal rate and TAI_MODULE_ATTR_TRIBUTARY_MAPPING. We need to care as there may be a combination of bitrate and modulation format that can not be set in the network interface.
In the future,  I want to add OTUCn and FlexE to client signal.

**Comment by ishidawataru** [comment]
@skuwa Thanks. Looks good to me.

As for Voyager and Cassini we can always return `TAI_HOST_INTERFACE_CLIENT_SIGNAL_RATE_100_GbE` for all host networks.

related PR : https://github.com/Telecominfraproject/oopt-tai/pull/66

@JumpeiHongo @scott-emery any comments?

**Comment by JumpeiHongo** [comment]
I also agree, if this is the attribute which is read only.

**Comment by JumpeiHongo** [comment]
If we add this as setting parameter, we need to care the Network interface. (ex. modulation format)
This may means the network interface(TAI module) should adjust automatically following the client rate setting.

What do you think about this? > all members.
I'd like to discuss the TAI's policy.

**Comment by JumpeiHongo** [comment]
@ishidawataru @skuwa 
I think we should discuss above thing in another issue.
So could you merge this attribute for reading and setting parameter?

**Comment by skuwa** [comment]
@ishidawataru @JumpeiHongo 
thanks for your comments.
I send pull request #79
