### ISSUE TITLE
Add BER Attribute to Network Interface Object

### ISSUE THREAD

**Issue by scott-emery** [Telecominfraproject/oopt-tai#8]
One of the key measures of quality of a network interface is the bit error rate (BER) of the interface. So I would like add the necessary attribute(s) to support BER for network interfaces. My initial thought is to add a read-only attribute which reports the current BER as a floating point number. In order to get an accurate understanding of the true error rate, the errors prior to any correction (i.e. before forward error correction (FEC) is applied) are the ones which should be used when making the calculation.

Since BER is a "rate", it implies that it is measured over a period of time, i.e. number of bit errors / total number of bits for a period of time. Should that "amount of time" be reported via TAI? The hardware I'm currently working with does the BER calculation in the hardware and simply provides that as a floating point number. It calculates the BER over the last 10 milliseconds, every 10 milliseconds. Other hardware may not perform the BER calculation, but instead rely more on software to periodically read the number of bit errors and perform the division. What are other people's experience with various hardware implementations to support BER?

My proposal is as follows:
```
    /**
     * @brief The current BER for the network interface
     *
     * @type #tai_float_t
     * @flags READ_ONLY
     */
    TAI_NETWORK_INTERFACE_ATTR_CURRENT_BER,
```

**Comment by ishidawataru** [comment]
> In order to get an accurate understanding of the true error rate, the errors prior to any correction (i.e. before forward error correction (FEC) is applied) are the ones which should be used when making the calculation.

I agree.

> Should that "amount of time" be reported via TAI? 

Yes, I think it's better to have it.

> What are other people's experience with various hardware implementations to support BER?

The platform I'm working with does BER calulation in software (DSP SDK).

**Comment by ishidawataru** [comment]
@scott-emery When the module has several hostifs, the platform we are using can get BER for each hostif. Is it same for you? In that case, it'd be better to put this attribute in hostif attribute.

**Comment by scott-emery** [comment]
@ishidawataru BER can be supported on every interface. The platform I'm working on calculates BER for each of the network interfaces **and** each of the host interfaces. So, yes, we can add it to the host interfaces, but it also needs to be included on the network interfaces.

The host interfaces are typically "internal" interfaces (between two chips inside the platform). So the BER is less critical on those interfaces, since those interfaces can be measured and tuned, and will not vary much once appropriate values are determined for their configuration.

The network interfaces, on the other hand, are typically "external" interfaces. We have no control over what they connect to, so those interfaces cannot be tuned just one way which will work in all environments. For this reason it is very important to have the ability to measure the quality of the network interface. This is why I started with a proposal for BER on the network interface. In the future we can also add it to the host interface object.

**Comment by ishidawataru** [comment]
I should have said that the platform I'm using can get BER for each host(client) traffic which goes through a network interface.

For example, if 2 host interfaces are connected to a network interface, 2 streams go through a network interface. I can get BER for each stream.

I defined a component named optical channel for this purpose which is removed now.

https://github.com/Telecominfraproject/OOPT-DTC-TAI/commit/43ac95387ea3a76ee76d4a61ede46216c57543ad#diff-74addb1093024ff9db91b4264e144f6f

We could revive this optical channel as a subcomponent of network interface.

**Comment by scott-emery** [comment]
Oh, I see. The platform I'm working on calls that a "tributary". When multiple host interfaces transmit into, and receive from, a single network interface, the data on the network interface for a single host interface is called a tributary.

Although it may be another data point, I don't see the use of individual optical channel (tributary) BER. Are there parameters that can be changed on a individual optical channel which can affect the signal quality only on that one optical channel, and not on the other optical channels within the same network interface?

The platform I'm working with does not have any configuration values which affect the signal quality of individual optical channels, just on the network interface. So changing the configuration affects all optical channels, and thus the BER of all optical channels.

**Comment by ishidawataru** [comment]
@scott-emery After some study, I came to agree with you.
I'll implement this by taking the average of both BERs.

**Comment by scott-emery** [comment]
Network Interface BER is now part of TAI.
